### ISSUE TITLE
Ticket VIews

### ISSUE THREAD

**Issue by AlhMaria** [aitorbouzas/helpdesk#15]
- Form
- List
  - Number
  - Name
  - Partner
  - User
  - State
  - Priority
- Kanban
- Pivot

**Comment by aitorbouzas** [comment]
@AlhMaria we are about to PR the menus and actions, when do you plan to finish this?

**Comment by aitorbouzas** [comment]
Also remember that ticket views should contain 'company_id' field for multicompany purposes.
